-- Manual / local regression checks for merged-profile re-login
-- (identity transfer: secondary Google/email → canonical auth user).
--
-- Run against a disposable local Supabase DB as a role that can call
-- admin_merge_profiles (or via service_role + set admin claims).
-- Do NOT run against production.
--
-- Expected outcomes after a fresh merge A → B:
--   1. profiles: only B remains; A gone
--   2. user_emails for both emails → user_id = B
--   3. auth.identities that belonged to A (and other auth uids for A's emails)
--      now have user_id = B; auth.users A is deleted (not banned)
--   4. exactly one profile_merge_transactions row for the pair
--   5. second admin_merge_profiles(A,B) returns { success: true, noop: true }
--   6. no second merge transaction row
--
-- Sign-in / sign-up (app-level):
--   - Email/Google for B → session for B, profile B
--   - Google that was on A → session for B, profile B (identities claimed)
--   - Email+password that existed only on A → password is NOT copied;
--     use Google linked to B, or password reset / magic link on B
--   - Leftover JWT for deleted A → get_login_account_status() returns
--     merged_into_other_account or auth_user_missing; client signs out
--   - Sign-up with Email A while email is on B’s user_emails and B has
--     active auth → aborted with "already linked"

-- Example sketch (replace UUIDs):
--
-- SELECT public.admin_merge_profiles(
--   'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'::uuid,  -- source A
--   'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid   -- target B
-- );
--
-- SELECT user_id, provider, email FROM auth.identities
-- WHERE email IN ('a@example.com', 'b@example.com');
-- -- all rows should show user_id = B
--
-- SELECT id FROM auth.users WHERE id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
-- -- should return 0 rows
