// ─── AUTO-GENERATED — DO NOT EDIT ────────────────────────────────────────────
// Generated by: scripts/generate-api-catalog.ts
// Regenerate with: node --import jiti/register scripts/generate-api-catalog.ts
// Last generated: 2026-03-04
//
// Entries: 110 (6 Vercel + 8 Edge + 96 RPC)

import type { ApiCatalogEntry } from './types';

export const generatedCatalog: ApiCatalogEntry[] = [
  {
    "id": "http-api-webhooks-momo",
    "kind": "http",
    "name": "Momo",
    "method": "POST",
    "path": "/api/webhooks/momo",
    "source_files": [
      "api/webhooks/momo.ts"
    ],
    "auth_level": "public",
    "roles_allowed": [],
    "callability": "disabled",
    "risk": "critical",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "webhook"
    ],
    "summary": "POST /api/webhooks/momo",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "http-api-og-expense",
    "kind": "http",
    "name": "Expense",
    "method": "GET",
    "path": "/api/og/expense",
    "source_files": [
      "api/og/expense.tsx"
    ],
    "auth_level": "public",
    "roles_allowed": [],
    "callability": "direct_http",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [
      "og"
    ],
    "summary": "GET /api/og/expense",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "http-api-debt-who-owes-who",
    "kind": "http",
    "name": "Who Owes Who",
    "method": "GET",
    "path": "/api/debt/who-owes-who",
    "source_files": [
      "api/debt/who-owes-who.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "proxy_admin",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [
      "debt",
      "admin"
    ],
    "summary": "GET /api/debt/who-owes-who",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "http-api-debt-all-users-summary",
    "kind": "http",
    "name": "All Users Summary",
    "method": "GET",
    "path": "/api/debt/all-users-summary",
    "source_files": [
      "api/debt/all-users-summary.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "proxy_admin",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [
      "debt",
      "admin"
    ],
    "summary": "GET /api/debt/all-users-summary",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "http-api-debt-all-users-detailed",
    "kind": "http",
    "name": "All Users Detailed",
    "method": "GET",
    "path": "/api/debt/all-users-detailed",
    "source_files": [
      "api/debt/all-users-detailed.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "proxy_admin",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [
      "debt",
      "admin"
    ],
    "summary": "GET /api/debt/all-users-detailed",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "http-api-admin-api-console-execute",
    "kind": "http",
    "name": "Execute",
    "method": "POST",
    "path": "/api/admin/api-console/execute",
    "source_files": [
      "api/admin/api-console/execute.ts"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "disabled",
    "risk": "medium",
    "used_in_code": true,
    "status": "active",
    "tags": [
      "admin"
    ],
    "summary": "POST /api/admin/api-console/execute",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-sepay-webhook",
    "kind": "http",
    "name": "Edge: Sepay Webhook",
    "method": "POST",
    "path": "/functions/v1/sepay-webhook",
    "source_files": [
      "supabase/functions/sepay-webhook/index.ts"
    ],
    "auth_level": "public",
    "roles_allowed": [],
    "callability": "disabled",
    "risk": "critical",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "sepay",
      "edge"
    ],
    "summary": "POST /functions/v1/sepay-webhook",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-sepay-create-order",
    "kind": "http",
    "name": "Edge: Sepay Create Order",
    "method": "POST",
    "path": "/functions/v1/sepay-create-order",
    "source_files": [
      "supabase/functions/sepay-create-order/index.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_http",
    "risk": "medium",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "sepay",
      "edge"
    ],
    "summary": "POST /functions/v1/sepay-create-order",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-send-email-notifications",
    "kind": "http",
    "name": "Edge: Send Email Notifications",
    "method": "POST",
    "path": "/functions/v1/send-email-notifications",
    "source_files": [
      "supabase/functions/send-email-notifications/index.ts"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "proxy_admin",
    "risk": "high",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "send",
      "edge"
    ],
    "summary": "POST /functions/v1/send-email-notifications",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-process-recurring-expenses",
    "kind": "http",
    "name": "Edge: Process Recurring Expenses",
    "method": "POST",
    "path": "/functions/v1/process-recurring-expenses",
    "source_files": [
      "supabase/functions/process-recurring-expenses/index.ts"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "proxy_admin",
    "risk": "high",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "process",
      "edge"
    ],
    "summary": "POST /functions/v1/process-recurring-expenses",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-get-user-debt",
    "kind": "http",
    "name": "Edge: Get User Debt",
    "method": "POST",
    "path": "/functions/v1/get-user-debt",
    "source_files": [
      "supabase/functions/get-user-debt/index.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_http",
    "risk": "medium",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "get",
      "edge"
    ],
    "summary": "POST /functions/v1/get-user-debt",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-all-users-debt-summary",
    "kind": "http",
    "name": "Edge: All Users Debt Summary",
    "method": "POST",
    "path": "/functions/v1/all-users-debt-summary",
    "source_files": [
      "supabase/functions/all-users-debt-summary/index.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_http",
    "risk": "medium",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "all",
      "edge"
    ],
    "summary": "POST /functions/v1/all-users-debt-summary",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-all-users-debt-detailed",
    "kind": "http",
    "name": "Edge: All Users Debt Detailed",
    "method": "POST",
    "path": "/functions/v1/all-users-debt-detailed",
    "source_files": [
      "supabase/functions/all-users-debt-detailed/index.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_http",
    "risk": "medium",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "all",
      "edge"
    ],
    "summary": "POST /functions/v1/all-users-debt-detailed",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "edge-ai-chat",
    "kind": "http",
    "name": "Edge: Ai Chat",
    "method": "POST",
    "path": "/functions/v1/ai-chat",
    "source_files": [
      "supabase/functions/ai-chat/index.ts"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_http",
    "risk": "medium",
    "used_in_code": false,
    "status": "active",
    "tags": [
      "ai",
      "edge"
    ],
    "summary": "POST /functions/v1/ai-chat",
    "params": [],
    "response_examples": [],
    "provenance": [
      "code"
    ]
  },
  {
    "id": "rpc-update-updated-at-column",
    "kind": "rpc",
    "name": "update_updated_at_column",
    "function_name": "update_updated_at_column",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: update_updated_at_column",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-handle-new-user",
    "kind": "rpc",
    "name": "handle_new_user",
    "function_name": "handle_new_user",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260226600000_fix_should_send_notification_defaults.sql",
      "supabase/migrations/20260211000000_create_claim_pending_email_function.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: handle_new_user",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-add-creator-as-admin",
    "kind": "rpc",
    "name": "add_creator_as_admin",
    "function_name": "add_creator_as_admin",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: add_creator_as_admin",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-auto-create-friendships-from-group",
    "kind": "rpc",
    "name": "auto_create_friendships_from_group",
    "function_name": "auto_create_friendships_from_group",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: auto_create_friendships_from_group",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-notify-friend-request",
    "kind": "rpc",
    "name": "notify_friend_request",
    "function_name": "notify_friend_request",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260226400000_fix_notification_triggers_robust.sql",
      "supabase/migrations/20260226100000_update_notification_functions_actor_id.sql",
      "supabase/migrations/20260107175703_friend_request_notifications.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: notify_friend_request",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-update-donation-settings-updated-at",
    "kind": "rpc",
    "name": "update_donation_settings_updated_at",
    "function_name": "update_donation_settings_updated_at",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: update_donation_settings_updated_at",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-is-admin",
    "kind": "rpc",
    "name": "is_admin",
    "function_name": "is_admin",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260108110000_momo_payment_integration.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: is_admin",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-user-is-group-member",
    "kind": "rpc",
    "name": "user_is_group_member",
    "function_name": "user_is_group_member",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: user_is_group_member",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-get-friendship",
    "kind": "rpc",
    "name": "get_friendship",
    "function_name": "get_friendship",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_friendship",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-are-friends",
    "kind": "rpc",
    "name": "are_friends",
    "function_name": "are_friends",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: are_friends",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-get-user-balance",
    "kind": "rpc",
    "name": "get_user_balance",
    "function_name": "get_user_balance",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260201100000_add_date_range_to_balance_functions.sql",
      "supabase/migrations/20260112004633_fix_get_user_balance_settlement_logic.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_balance",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-debts-aggregated",
    "kind": "rpc",
    "name": "get_user_debts_aggregated",
    "function_name": "get_user_debts_aggregated",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260211200000_fix_max_uuid_in_debt_aggregation.sql",
      "supabase/migrations/20260211100000_include_pending_email_in_debt_aggregation.sql",
      "supabase/migrations/20260209100000_fix_debt_netting_and_rounding.sql",
      "supabase/migrations/20260206160000_filter_zero_balance_from_debts_aggregated.sql",
      "supabase/migrations/20260206130000_fix_get_user_debts_aggregated_overload.sql",
      "supabase/migrations/20260201100000_add_date_range_to_balance_functions.sql",
      "supabase/migrations/20260109130000_update_debt_functions_currency.sql",
      "supabase/migrations/20260109100000_add_currency_to_debt_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_debts_aggregated",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-debts-history",
    "kind": "rpc",
    "name": "get_user_debts_history",
    "function_name": "get_user_debts_history",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260109130000_update_debt_functions_currency.sql",
      "supabase/migrations/20260109100000_add_currency_to_debt_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_debts_history",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-simplify-group-debts",
    "kind": "rpc",
    "name": "simplify_group_debts",
    "function_name": "simplify_group_debts",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260227100000_fix_simplify_group_debts_ambiguous_amount.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: simplify_group_debts",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-settle-split",
    "kind": "rpc",
    "name": "settle_split",
    "function_name": "settle_split",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260206000002_fix_settle_split_pending_email.sql",
      "supabase/migrations/20260112040000_update_settle_split_insert_events.sql",
      "supabase/migrations/20260112020000_update_settle_split_partial_support.sql",
      "supabase/migrations/20260110100000_add_admin_permissions_to_settle_operations.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: settle_split",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-unsettle-split",
    "kind": "rpc",
    "name": "unsettle_split",
    "function_name": "unsettle_split",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260110100000_add_admin_permissions_to_settle_operations.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: unsettle_split",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-settle-expense",
    "kind": "rpc",
    "name": "settle_expense",
    "function_name": "settle_expense",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260110100000_add_admin_permissions_to_settle_operations.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: settle_expense",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-get-expense-splits-public",
    "kind": "rpc",
    "name": "get_expense_splits_public",
    "function_name": "get_expense_splits_public",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260206000001_fix_expense_splits_pending_email_join.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_expense_splits_public",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-get-leaderboard-data",
    "kind": "rpc",
    "name": "get_leaderboard_data",
    "function_name": "get_leaderboard_data",
    "source_files": [
      "supabase/baseline.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_leaderboard_data",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline"
    ]
  },
  {
    "id": "rpc-calculate-next-occurrence",
    "kind": "rpc",
    "name": "calculate_next_occurrence",
    "function_name": "calculate_next_occurrence",
    "source_files": [
      "supabase/baseline.sql",
      "supabase/migrations/20260215120000_fix_recurring_functions_schema.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: calculate_next_occurrence",
    "params": [],
    "response_examples": [],
    "provenance": [
      "baseline",
      "migration"
    ]
  },
  {
    "id": "rpc-get-expense-og-data",
    "kind": "rpc",
    "name": "get_expense_og_data",
    "function_name": "get_expense_og_data",
    "source_files": [
      "supabase/migrations/20260304010000_fix_get_expense_og_data_type_casts.sql",
      "supabase/migrations/20260304000000_create_get_expense_og_data.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_expense_og_data",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-settle-splits-batch",
    "kind": "rpc",
    "name": "settle_splits_batch",
    "function_name": "settle_splits_batch",
    "source_files": [
      "supabase/migrations/20260302000000_fix_settle_batch_payment_events.sql",
      "supabase/migrations/20260226000001_fix_settle_authorization.sql",
      "supabase/migrations/20260209130000_create_settle_splits_batch_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: settle_splits_batch",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-settle-all-group-debts",
    "kind": "rpc",
    "name": "settle_all_group_debts",
    "function_name": "settle_all_group_debts",
    "source_files": [
      "supabase/migrations/20260302000000_fix_settle_batch_payment_events.sql",
      "supabase/migrations/20260110100000_add_admin_permissions_to_settle_operations.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: settle_all_group_debts",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-email-notification-queue",
    "kind": "rpc",
    "name": "get_email_notification_queue",
    "function_name": "get_email_notification_queue",
    "source_files": [
      "supabase/migrations/20260227200000_add_email_notifications_worker.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_email_notification_queue",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-add-expense-comment",
    "kind": "rpc",
    "name": "add_expense_comment",
    "function_name": "add_expense_comment",
    "source_files": [
      "supabase/migrations/20260227000000_open_comment_reaction_to_all_authenticated.sql",
      "supabase/migrations/20260226800000_fix_comment_reaction_notifications_and_anchors.sql",
      "supabase/migrations/20260226500000_fix_missing_actor_id_in_notifications.sql",
      "supabase/migrations/20260225100000_notify_participants_on_comment_and_reaction.sql",
      "supabase/migrations/20260218110000_comment_mention_enhancements.sql",
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: add_expense_comment",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-toggle-reaction",
    "kind": "rpc",
    "name": "toggle_reaction",
    "function_name": "toggle_reaction",
    "source_files": [
      "supabase/migrations/20260227000000_open_comment_reaction_to_all_authenticated.sql",
      "supabase/migrations/20260226800000_fix_comment_reaction_notifications_and_anchors.sql",
      "supabase/migrations/20260226500000_fix_missing_actor_id_in_notifications.sql",
      "supabase/migrations/20260225100000_notify_participants_on_comment_and_reaction.sql",
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: toggle_reaction",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-expense-comments",
    "kind": "rpc",
    "name": "get_expense_comments",
    "function_name": "get_expense_comments",
    "source_files": [
      "supabase/migrations/20260227000000_open_comment_reaction_to_all_authenticated.sql",
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_expense_comments",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-broadcast-notification-insert",
    "kind": "rpc",
    "name": "broadcast_notification_insert",
    "function_name": "broadcast_notification_insert",
    "source_files": [
      "supabase/migrations/20260226900000_fix_realtime_notifications_broadcast.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: broadcast_notification_insert",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-log-table-changes",
    "kind": "rpc",
    "name": "log_table_changes",
    "function_name": "log_table_changes",
    "source_files": [
      "supabase/migrations/20260226600000_fix_should_send_notification_defaults.sql",
      "supabase/migrations/20260224000000_fix_audit_logs_column_mismatch.sql",
      "supabase/migrations/20260217000000_comprehensive_audit_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: log_table_changes",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-notify-admins-on-join-request",
    "kind": "rpc",
    "name": "notify_admins_on_join_request",
    "function_name": "notify_admins_on_join_request",
    "source_files": [
      "supabase/migrations/20260226500000_fix_missing_actor_id_in_notifications.sql",
      "supabase/migrations/20260216210000_notify_admins_on_join_request.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: notify_admins_on_join_request",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-notify-friend-accepted",
    "kind": "rpc",
    "name": "notify_friend_accepted",
    "function_name": "notify_friend_accepted",
    "source_files": [
      "supabase/migrations/20260226400000_fix_notification_triggers_robust.sql",
      "supabase/migrations/20260226200000_fix_missing_notification_triggers.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: notify_friend_accepted",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-notify-added-to-group",
    "kind": "rpc",
    "name": "notify_added_to_group",
    "function_name": "notify_added_to_group",
    "source_files": [
      "supabase/migrations/20260226400000_fix_notification_triggers_robust.sql",
      "supabase/migrations/20260226200000_fix_missing_notification_triggers.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: notify_added_to_group",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-notify-payment-recorded",
    "kind": "rpc",
    "name": "notify_payment_recorded",
    "function_name": "notify_payment_recorded",
    "source_files": [
      "supabase/migrations/20260226400000_fix_notification_triggers_robust.sql",
      "supabase/migrations/20260226200000_fix_missing_notification_triggers.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: notify_payment_recorded",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-approve-join-request",
    "kind": "rpc",
    "name": "approve_join_request",
    "function_name": "approve_join_request",
    "source_files": [
      "supabase/migrations/20260226400000_fix_notification_triggers_robust.sql",
      "supabase/migrations/20260226200000_fix_missing_notification_triggers.sql",
      "supabase/migrations/20260216200000_group_join_requests.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: approve_join_request",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-reject-join-request",
    "kind": "rpc",
    "name": "reject_join_request",
    "function_name": "reject_join_request",
    "source_files": [
      "supabase/migrations/20260226400000_fix_notification_triggers_robust.sql",
      "supabase/migrations/20260226200000_fix_missing_notification_triggers.sql",
      "supabase/migrations/20260216200000_group_join_requests.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: reject_join_request",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-auto-fill-notification-actor-id",
    "kind": "rpc",
    "name": "auto_fill_notification_actor_id",
    "function_name": "auto_fill_notification_actor_id",
    "source_files": [
      "supabase/migrations/20260226300000_add_actor_id_to_comment_reaction_notifications.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: auto_fill_notification_actor_id",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-admin-revert-audit-entry",
    "kind": "rpc",
    "name": "admin_revert_audit_entry",
    "function_name": "admin_revert_audit_entry",
    "source_files": [
      "supabase/migrations/20260226100000_admin_revert_audit_entry.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: admin_revert_audit_entry",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-settle-all-splits-for-user",
    "kind": "rpc",
    "name": "settle_all_splits_for_user",
    "function_name": "settle_all_splits_for_user",
    "source_files": [
      "supabase/migrations/20260226000001_fix_settle_authorization.sql",
      "supabase/migrations/20260206000003_fix_all_settle_functions_pending_email.sql",
      "supabase/migrations/20260112155602_create_settle_all_splits_for_user_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: settle_all_splits_for_user",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-settle-all-debts-with-person",
    "kind": "rpc",
    "name": "settle_all_debts_with_person",
    "function_name": "settle_all_debts_with_person",
    "source_files": [
      "supabase/migrations/20260226000001_fix_settle_authorization.sql",
      "supabase/migrations/20260206000003_fix_all_settle_functions_pending_email.sql",
      "supabase/migrations/20260112080000_create_settle_all_debts_with_person_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: settle_all_debts_with_person",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-broadcast-notification",
    "kind": "rpc",
    "name": "broadcast_notification",
    "function_name": "broadcast_notification",
    "source_files": [
      "supabase/migrations/20260225600000_notification_broadcast_trigger.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: broadcast_notification",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-delete-expense-notifications",
    "kind": "rpc",
    "name": "delete_expense_notifications",
    "function_name": "delete_expense_notifications",
    "source_files": [
      "supabase/migrations/20260225200000_cascade_delete_notifications_on_expense_delete.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: delete_expense_notifications",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-bulk-delete-expenses",
    "kind": "rpc",
    "name": "bulk_delete_expenses",
    "function_name": "bulk_delete_expenses",
    "source_files": [
      "supabase/migrations/20260224000000_fix_audit_logs_column_mismatch.sql",
      "supabase/migrations/20260209110000_fix_bulk_delete_audit_log_columns.sql",
      "supabase/migrations/20260110100000_add_admin_permissions_to_settle_operations.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "critical",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: bulk_delete_expenses",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-read-admin-audit-logs",
    "kind": "rpc",
    "name": "read_admin_audit_logs",
    "function_name": "read_admin_audit_logs",
    "source_files": [
      "supabase/migrations/20260224000000_fix_audit_logs_column_mismatch.sql",
      "supabase/migrations/20260217000000_comprehensive_audit_system.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: read_admin_audit_logs",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-audit-stats",
    "kind": "rpc",
    "name": "get_audit_stats",
    "function_name": "get_audit_stats",
    "source_files": [
      "supabase/migrations/20260224000000_fix_audit_logs_column_mismatch.sql",
      "supabase/migrations/20260217000000_comprehensive_audit_system.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_audit_stats",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-audit-filter-options",
    "kind": "rpc",
    "name": "get_audit_filter_options",
    "function_name": "get_audit_filter_options",
    "source_files": [
      "supabase/migrations/20260224000000_fix_audit_logs_column_mismatch.sql",
      "supabase/migrations/20260217000000_comprehensive_audit_system.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_audit_filter_options",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-expire-pending-actions",
    "kind": "rpc",
    "name": "expire_pending_actions",
    "function_name": "expire_pending_actions",
    "source_files": [
      "supabase/migrations/20260222000000_ai_chat_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: expire_pending_actions",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-update-conversation-timestamp",
    "kind": "rpc",
    "name": "update_conversation_timestamp",
    "function_name": "update_conversation_timestamp",
    "source_files": [
      "supabase/migrations/20260222000000_ai_chat_system.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: update_conversation_timestamp",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-upsert-emoji-reaction-type",
    "kind": "rpc",
    "name": "upsert_emoji_reaction_type",
    "function_name": "upsert_emoji_reaction_type",
    "source_files": [
      "supabase/migrations/20260218150000_fix_upsert_emoji_gen_random.sql",
      "supabase/migrations/20260218140000_upsert_emoji_reaction_type.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: upsert_emoji_reaction_type",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-update-expense-comment",
    "kind": "rpc",
    "name": "update_expense_comment",
    "function_name": "update_expense_comment",
    "source_files": [
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: update_expense_comment",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-delete-expense-comment",
    "kind": "rpc",
    "name": "delete_expense_comment",
    "function_name": "delete_expense_comment",
    "source_files": [
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: delete_expense_comment",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-reactions",
    "kind": "rpc",
    "name": "get_reactions",
    "function_name": "get_reactions",
    "source_files": [
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_reactions",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-expense-all-reactions",
    "kind": "rpc",
    "name": "get_expense_all_reactions",
    "function_name": "get_expense_all_reactions",
    "source_files": [
      "supabase/migrations/20260218100000_comment_reaction_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_expense_all_reactions",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-admin-update-user-role",
    "kind": "rpc",
    "name": "admin_update_user_role",
    "function_name": "admin_update_user_role",
    "source_files": [
      "supabase/migrations/20260218000000_admin_update_user_role_rpc.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "critical",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: admin_update_user_role",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-cleanup-old-audit-logs",
    "kind": "rpc",
    "name": "cleanup_old_audit_logs",
    "function_name": "cleanup_old_audit_logs",
    "source_files": [
      "supabase/migrations/20260217000000_comprehensive_audit_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: cleanup_old_audit_logs",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-group-member-count",
    "kind": "rpc",
    "name": "get_group_member_count",
    "function_name": "get_group_member_count",
    "source_files": [
      "supabase/migrations/20260216200000_group_join_requests.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_group_member_count",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-all-groups-with-member-counts",
    "kind": "rpc",
    "name": "get_all_groups_with_member_counts",
    "function_name": "get_all_groups_with_member_counts",
    "source_files": [
      "supabase/migrations/20260216200000_group_join_requests.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_all_groups_with_member_counts",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-due-recurring-expenses",
    "kind": "rpc",
    "name": "get_due_recurring_expenses",
    "function_name": "get_due_recurring_expenses",
    "source_files": [
      "supabase/migrations/20260215120000_fix_recurring_functions_schema.sql",
      "supabase/migrations/20260114200000_update_get_due_recurring_expenses_prepaid.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_due_recurring_expenses",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-process-single-recurring-instance",
    "kind": "rpc",
    "name": "process_single_recurring_instance",
    "function_name": "process_single_recurring_instance",
    "source_files": [
      "supabase/migrations/20260215120000_fix_recurring_functions_schema.sql",
      "supabase/migrations/20260215110000_process_recurring_instance_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: process_single_recurring_instance",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-admin-stats",
    "kind": "rpc",
    "name": "get_admin_stats",
    "function_name": "get_admin_stats",
    "source_files": [
      "supabase/migrations/20260214100000_admin_stats_with_trends.sql",
      "supabase/migrations/20260213100000_fix_admin_stats_deleted_at.sql",
      "supabase/migrations/20260212000000_admin_dashboard_setup.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_admin_stats",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-admin-accept-friendship",
    "kind": "rpc",
    "name": "admin_accept_friendship",
    "function_name": "admin_accept_friendship",
    "source_files": [
      "supabase/migrations/20260213200000_admin_accept_friendship.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "critical",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: admin_accept_friendship",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-admin-users",
    "kind": "rpc",
    "name": "get_admin_users",
    "function_name": "get_admin_users",
    "source_files": [
      "supabase/migrations/20260213000000_admin_users_rpc.sql"
    ],
    "auth_level": "admin",
    "roles_allowed": [
      "admin"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_admin_users",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-claim-pending-email-splits",
    "kind": "rpc",
    "name": "claim_pending_email_splits",
    "function_name": "claim_pending_email_splits",
    "source_files": [
      "supabase/migrations/20260211000000_create_claim_pending_email_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: claim_pending_email_splits",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-who-owes-who",
    "kind": "rpc",
    "name": "get_who_owes_who",
    "function_name": "get_who_owes_who",
    "source_files": [
      "supabase/migrations/20260209125000_create_who_owes_who_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_who_owes_who",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-all-users-debt-detailed",
    "kind": "rpc",
    "name": "get_all_users_debt_detailed",
    "function_name": "get_all_users_debt_detailed",
    "source_files": [
      "supabase/migrations/20260206150000_fix_max_uuid_error.sql",
      "supabase/migrations/20260206140000_populate_debts_by_person_and_group.sql",
      "supabase/migrations/20260206120000_create_all_users_debt_endpoints.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_all_users_debt_detailed",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-all-users-debt-summary",
    "kind": "rpc",
    "name": "get_all_users_debt_summary",
    "function_name": "get_all_users_debt_summary",
    "source_files": [
      "supabase/migrations/20260206120000_create_all_users_debt_endpoints.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_all_users_debt_summary",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-debt-by-secret",
    "kind": "rpc",
    "name": "get_user_debt_by_secret",
    "function_name": "get_user_debt_by_secret",
    "source_files": [
      "supabase/migrations/20260206100000_create_public_debt_api_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_debt_by_secret",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-create-api-secret",
    "kind": "rpc",
    "name": "create_api_secret",
    "function_name": "create_api_secret",
    "source_files": [
      "supabase/migrations/20260206100000_create_public_debt_api_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: create_api_secret",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-list-api-secrets",
    "kind": "rpc",
    "name": "list_api_secrets",
    "function_name": "list_api_secrets",
    "source_files": [
      "supabase/migrations/20260206100000_create_public_debt_api_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: list_api_secrets",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-revoke-api-secret",
    "kind": "rpc",
    "name": "revoke_api_secret",
    "function_name": "revoke_api_secret",
    "source_files": [
      "supabase/migrations/20260206100000_create_public_debt_api_system.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: revoke_api_secret",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-settle-all-splits",
    "kind": "rpc",
    "name": "settle_all_splits",
    "function_name": "settle_all_splits",
    "source_files": [
      "supabase/migrations/20260206000003_fix_all_settle_functions_pending_email.sql",
      "supabase/migrations/20260112050000_create_settle_all_splits_function.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: settle_all_splits",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-record-member-prepaid",
    "kind": "rpc",
    "name": "record_member_prepaid",
    "function_name": "record_member_prepaid",
    "source_files": [
      "supabase/migrations/20260115400000_fix_record_member_prepaid.sql",
      "supabase/migrations/20260115150000_enhance_prepaid_error_logging.sql",
      "supabase/migrations/20260115110000_member_prepaid_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: record_member_prepaid",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-all-members-prepaid-info",
    "kind": "rpc",
    "name": "get_all_members_prepaid_info",
    "function_name": "get_all_members_prepaid_info",
    "source_files": [
      "supabase/migrations/20260115200000_fix_prepaid_info_ambiguous_column.sql",
      "supabase/migrations/20260115110000_member_prepaid_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_all_members_prepaid_info",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-create-recurring-instance",
    "kind": "rpc",
    "name": "create_recurring_instance",
    "function_name": "create_recurring_instance",
    "source_files": [
      "supabase/migrations/20260115120000_integrate_prepaid_consumption.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: create_recurring_instance",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-create-recurring-instance-manual",
    "kind": "rpc",
    "name": "create_recurring_instance_manual",
    "function_name": "create_recurring_instance_manual",
    "source_files": [
      "supabase/migrations/20260115120000_integrate_prepaid_consumption.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: create_recurring_instance_manual",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-member-monthly-share",
    "kind": "rpc",
    "name": "get_member_monthly_share",
    "function_name": "get_member_monthly_share",
    "source_files": [
      "supabase/migrations/20260115110000_member_prepaid_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_member_monthly_share",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-record-multi-member-prepaid",
    "kind": "rpc",
    "name": "record_multi_member_prepaid",
    "function_name": "record_multi_member_prepaid",
    "source_files": [
      "supabase/migrations/20260115110000_member_prepaid_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: record_multi_member_prepaid",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-consume-prepaid-for-instance",
    "kind": "rpc",
    "name": "consume_prepaid_for_instance",
    "function_name": "consume_prepaid_for_instance",
    "source_files": [
      "supabase/migrations/20260115110000_member_prepaid_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: consume_prepaid_for_instance",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-record-prepaid-payment",
    "kind": "rpc",
    "name": "record_prepaid_payment",
    "function_name": "record_prepaid_payment",
    "source_files": [
      "supabase/migrations/20260114300000_add_paid_by_to_prepaid_payment.sql",
      "supabase/migrations/20260114100000_recurring_prepaid_payment_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: record_prepaid_payment",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-calculate-prepaid-until",
    "kind": "rpc",
    "name": "calculate_prepaid_until",
    "function_name": "calculate_prepaid_until",
    "source_files": [
      "supabase/migrations/20260114100000_recurring_prepaid_payment_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: calculate_prepaid_until",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-prepaid-payment-history",
    "kind": "rpc",
    "name": "get_prepaid_payment_history",
    "function_name": "get_prepaid_payment_history",
    "source_files": [
      "supabase/migrations/20260114100000_recurring_prepaid_payment_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_prepaid_payment_history",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-expense-payment-events",
    "kind": "rpc",
    "name": "get_expense_payment_events",
    "function_name": "get_expense_payment_events",
    "source_files": [
      "supabase/migrations/20260112070000_create_get_expense_payment_events.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_expense_payment_events",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-expenses-with-payment-events",
    "kind": "rpc",
    "name": "get_expenses_with_payment_events",
    "function_name": "get_expenses_with_payment_events",
    "source_files": [
      "supabase/migrations/20260112070000_create_get_expense_payment_events.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_expenses_with_payment_events",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-verify-momo-payment",
    "kind": "rpc",
    "name": "verify_momo_payment",
    "function_name": "verify_momo_payment",
    "source_files": [
      "supabase/migrations/20260112060000_update_momo_payment_insert_events.sql",
      "supabase/migrations/20260108110000_momo_payment_integration.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: verify_momo_payment",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-write-audit-trail",
    "kind": "rpc",
    "name": "write_audit_trail",
    "function_name": "write_audit_trail",
    "source_files": [
      "supabase/migrations/20260112010000_create_audit_trail_rpc_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: write_audit_trail",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-read-audit-trail",
    "kind": "rpc",
    "name": "read_audit_trail",
    "function_name": "read_audit_trail",
    "source_files": [
      "supabase/migrations/20260112010000_create_audit_trail_rpc_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: read_audit_trail",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-debts-public",
    "kind": "rpc",
    "name": "get_user_debts_public",
    "function_name": "get_user_debts_public",
    "source_files": [
      "supabase/migrations/20260111044424_fix_public_demo_data_function_overload.sql",
      "supabase/migrations/20260111044236_enhance_public_demo_data_with_admin_config.sql",
      "supabase/migrations/20260111044236_enhance_public_demo_data_with_admin_config.sql",
      "supabase/migrations/20260111000000_fix_get_user_debts_public_multiple_users.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: get_user_debts_public",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-soft-delete-expense",
    "kind": "rpc",
    "name": "soft_delete_expense",
    "function_name": "soft_delete_expense",
    "source_files": [
      "supabase/migrations/20260110100000_add_admin_permissions_to_settle_operations.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: soft_delete_expense",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-balance-history",
    "kind": "rpc",
    "name": "get_balance_history",
    "function_name": "get_balance_history",
    "source_files": [
      "supabase/migrations/20260110000000_fix_sql_function_errors.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_balance_history",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-top-categories",
    "kind": "rpc",
    "name": "get_top_categories",
    "function_name": "get_top_categories",
    "source_files": [
      "supabase/migrations/20260110000000_fix_sql_function_errors.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_top_categories",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-activities",
    "kind": "rpc",
    "name": "get_user_activities",
    "function_name": "get_user_activities",
    "source_files": [
      "supabase/migrations/20260109140000_update_user_activities_privacy.sql",
      "supabase/migrations/20260109120000_fix_user_activities_pagination.sql",
      "supabase/migrations/20260108140000_fix_get_user_activities_unpaid.sql",
      "supabase/migrations/20260108130000_get_user_activities_function.sql",
      "supabase/migrations/20260108120000_create_get_user_activities.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_activities",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-balances",
    "kind": "rpc",
    "name": "get_user_balances",
    "function_name": "get_user_balances",
    "source_files": [
      "supabase/migrations/20260109100000_add_currency_to_debt_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_balances",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-user-balances-with-history",
    "kind": "rpc",
    "name": "get_user_balances_with_history",
    "function_name": "get_user_balances_with_history",
    "source_files": [
      "supabase/migrations/20260109100000_add_currency_to_debt_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_user_balances_with_history",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-get-public-demo-debts",
    "kind": "rpc",
    "name": "get_public_demo_debts",
    "function_name": "get_public_demo_debts",
    "source_files": [
      "supabase/migrations/20260109100000_add_currency_to_debt_functions.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "low",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: get_public_demo_debts",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-update-momo-settings-updated-at",
    "kind": "rpc",
    "name": "update_momo_settings_updated_at",
    "function_name": "update_momo_settings_updated_at",
    "source_files": [
      "supabase/migrations/20260108110000_momo_payment_integration.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: update_momo_settings_updated_at",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-update-momo-payment-requests-updated-at",
    "kind": "rpc",
    "name": "update_momo_payment_requests_updated_at",
    "function_name": "update_momo_payment_requests_updated_at",
    "source_files": [
      "supabase/migrations/20260108110000_momo_payment_integration.sql"
    ],
    "auth_level": "service_role",
    "roles_allowed": [
      "service_role"
    ],
    "callability": "disabled",
    "risk": "high",
    "used_in_code": false,
    "status": "unverified",
    "tags": [],
    "summary": "RPC function: update_momo_payment_requests_updated_at",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  },
  {
    "id": "rpc-create-momo-payment-request",
    "kind": "rpc",
    "name": "create_momo_payment_request",
    "function_name": "create_momo_payment_request",
    "source_files": [
      "supabase/migrations/20260108110000_momo_payment_integration.sql"
    ],
    "auth_level": "authenticated",
    "roles_allowed": [
      "authenticated"
    ],
    "callability": "direct_rpc",
    "risk": "high",
    "used_in_code": true,
    "status": "active",
    "tags": [],
    "summary": "RPC function: create_momo_payment_request",
    "params": [],
    "response_examples": [],
    "provenance": [
      "migration"
    ]
  }
];
