-- Migration: Add recurring_expense_id and cycle_date to expenses table
-- Description: Link generated expense instances back to their recurring parent
-- Required for: Idempotency checks, prepaid consumption, audit tracking

-- ========================================
-- SECTION 1: Add recurring_expense_id column
-- Links generated instances to parent recurring expense
-- ========================================

ALTER TABLE expenses
ADD COLUMN IF NOT EXISTS recurring_expense_id UUID REFERENCES recurring_expenses(id) ON DELETE SET NULL;

COMMENT ON COLUMN expenses.recurring_expense_id IS
'Reference to the recurring expense that generated this instance. NULL for manually created expenses.';

-- Index for efficient lookups
CREATE INDEX IF NOT EXISTS idx_expenses_recurring_expense_id
ON expenses(recurring_expense_id)
WHERE recurring_expense_id IS NOT NULL;

-- ========================================
-- SECTION 2: Add cycle_date column
-- The scheduled date this instance represents (for idempotency)
-- ========================================

ALTER TABLE expenses
ADD COLUMN IF NOT EXISTS cycle_date DATE;

COMMENT ON COLUMN expenses.cycle_date IS
'The recurring cycle date this expense instance represents. Used with recurring_expense_id for idempotency.';

-- ========================================
-- SECTION 3: Unique constraint for idempotency
-- Prevents duplicate instances for the same recurring expense + cycle date
-- ========================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_expenses_recurring_cycle_unique
ON expenses(recurring_expense_id, cycle_date)
WHERE recurring_expense_id IS NOT NULL AND cycle_date IS NOT NULL;

-- ========================================
-- SECTION 4: Add generated_at column for audit
-- Tracks when auto-generation happened
-- ========================================

ALTER TABLE expenses
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ;

COMMENT ON COLUMN expenses.generated_at IS
'Timestamp when this expense was auto-generated by the recurring system. NULL for manual expenses.';
